# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The Calm Betwixt Storms
description: An Embers of the Vale Adventure
baseurl: "/calm_betwixt_storms" # the subpath of your site, e.g. /blog
url: "https://lambdr.github.io" # the base hostname & protocol for your site, e.g. http://example.com

markdown: kramdown

include:
  - _pages

collections:
  recaps:
    output: true
    permalink: /recaps/:name/
  party:
    output: true
    permalink: /characters/party/:name/
  npcs:
    output: true
    permalink: /characters/npcs/:name/

defaults:
  - scope:
      path: ""
      type: recaps
    values:
      layout: default
  - scope:
      path: ""
      type: party
    values:
      layout: default
  - scope:
      path: ""
      type: npcs
    values:
      layout: default